sonar.projectKey=gcs-projeto
sonar.projectName=GCS Projeto 2026/A
sonar.projectVersion=1.0

sonar.sources=app,routes,database
sonar.tests=tests
sonar.language=php

sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.php.tests.reportPath=coverage/junit.xml

sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,coverage/**
sonar.test.exclusions=tests/**

sonar.host.url=http://sonarqube:9000
sonar.login=admin
sonar.password=admin
